name: publish-style-spec

on:
  workflow_dispatch

jobs:
  build_publish:
    name: Build, publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js 18 x64
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 18
          architecture: x64
          registry-url: 'https://registry.npmjs.org'

      - name: Install NPM packages
        run: npm ci
      
      - name: Build style spec
        run: |
          npm run build-style-spec
          npm run generate-typings
          npm run compile
      
      - name: Check version and publish
        run: |
          node -e "if(require('./package').version.includes('dev')) { process.exit(1) }"
          npm publish --access=public --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ORG_TOKEN }}
